name: Deploy Typst PDF to Pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  prepare-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true

      - name: Ensure yq is available
        run: |
          if ! command -v yq &> /dev/null; then
            sudo wget -qO /usr/local/bin/yq \
              https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi

      - name: Prepare metadata.yml
        env:
          STUDENT_FIRST_NAME: ${{ secrets.STUDENT_FIRST_NAME }}
          STUDENT_LAST_NAME:  ${{ secrets.STUDENT_LAST_NAME }}
          STUDENT_EMAIL:      ${{ secrets.STUDENT_EMAIL }}
          STUDENT_ID:         ${{ secrets.STUDENT_ID }}
        run: |
          mv example.metadata.yml metadata.yml

          yq -i '
            .studentFirstName = strenv(STUDENT_FIRST_NAME) |
            .studentLastName  = strenv(STUDENT_LAST_NAME)  |
            .studentEmail     = strenv(STUDENT_EMAIL)      |
            .studentID        = strenv(STUDENT_ID)
          ' metadata.yml

      - uses: actions/upload-artifact@v7
        with:
          name: metadata
          path: metadata.yml

      - uses: actions/upload-artifact@v7
        with:
          name: site-extras
          path: index.html

  # Deployment job
  deploy:
    needs: prepare-metadata
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: cr2007/actions/.github/workflows/typst-deploy.yml@v1
    with:
      source-file: main.typ
      output-file: coursework.pdf
      lfs: true
      extra-files-artifact: metadata
      extra-site-files-artifact: site-extras
